scalar Text

type StartGame {
  id: String!
  owner: String!
  adventurer_id: Int!
  no_message: Int!
  last_action: Int!
  health: Int!
  xp: Int!
  strength: Int!
  dexterity: Int!
  vitality: Int!
  intelligence: Int!
  wisdom: Int!
  charisma: Int!
  luck: Int!
  gold: Int!
  weapon_id: Int!
  weapon_xp: Int!
  weapon_metadata: Int!
  chest_id: Int!
  chest_xp: Int!
  chest_metadata: Int!
  head_id: Int!
  head_xp: Int!
  head_metadata: Int!
  waist_id: Int!
  waist_xp: Int!
  waist_metadata: Int!
  foot_id: Int!
  foot_xp: Int!
  foot_metadata: Int!
  hand_id: Int!
  hand_xp: Int!
  hand_metadata: Int!
  neck_id: Int!
  neck_xp: Int!
  neck_metadata: Int!
  ring_id: Int!
  ring_xp: Int!
  ring_metadata: Int!
  beast_health: Int!
  stat_points_available: Int!
  mutated: Int!
  name: String!
  home_realm: Int!
  clazz: Int!
  entropy: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type SlayedBeast {
  id: String!
  owner: String!
  adventurer_id: Int!
  no_message: Int!
  last_action: Int!
  health: Int!
  xp: Int!
  strength: Int!
  dexterity: Int!
  vitality: Int!
  intelligence: Int!
  wisdom: Int!
  charisma: Int!
  luck: Int!
  gold: Int!
  weapon_id: Int!
  weapon_xp: Int!
  weapon_metadata: Int!
  chest_id: Int!
  chest_xp: Int!
  chest_metadata: Int!
  head_id: Int!
  head_xp: Int!
  head_metadata: Int!
  waist_id: Int!
  waist_xp: Int!
  waist_metadata: Int!
  foot_id: Int!
  foot_xp: Int!
  foot_metadata: Int!
  hand_id: Int!
  hand_xp: Int!
  hand_metadata: Int!
  neck_id: Int!
  neck_xp: Int!
  neck_metadata: Int!
  ring_id: Int!
  ring_xp: Int!
  ring_metadata: Int!
  beast_health: Int!
  stat_points_available: Int!
  mutated: Int!
  seed: Int!
  slayed_beast_id: Int!
  tier: Int!
  item_type: Int!
  level: Int!
  special1: Int!
  special2: Int!
  special3: Int!
  damage_dealt: Int!
  critical_hit: Int!
  xp_earned_adventurer: Int!
  xp_earned_items: Int!
  gold_earned: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type RewardDistribution {
  id: String!
  first_place_adventurer_id: Int!
  first_place_no_message: Int!
  first_place_rank: Int!
  first_place_amount: Int!
  first_place_no_message_2: Int!
  first_place_address: String!
  second_place_adventurer_id: Int!
  second_place_no_message: Int!
  second_place_rank: Int!
  second_place_amount: Int!
  second_place_no_message_2: Int!
  second_place_address: String!
  third_place_adventurer_id: Int!
  third_place_no_message: Int!
  third_place_rank: Int!
  third_place_amount: Int!
  third_place_no_message_2: Int!
  third_place_address: String!
  client_amount: Int!
  client_no_message: Int!
  client_address: String!
  dao: Int!
  no_message: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type AdventurerLeveledUp {
  id: String!
  owner: String!
  adventurer_id: Int!
  no_message: Int!
  last_action: Int!
  health: Int!
  xp: Int!
  strength: Int!
  dexterity: Int!
  vitality: Int!
  intelligence: Int!
  wisdom: Int!
  charisma: Int!
  luck: Int!
  gold: Int!
  weapon_id: Int!
  weapon_xp: Int!
  weapon_metadata: Int!
  chest_id: Int!
  chest_xp: Int!
  chest_metadata: Int!
  head_id: Int!
  head_xp: Int!
  head_metadata: Int!
  waist_id: Int!
  waist_xp: Int!
  waist_metadata: Int!
  foot_id: Int!
  foot_xp: Int!
  foot_metadata: Int!
  hand_id: Int!
  hand_xp: Int!
  hand_metadata: Int!
  neck_id: Int!
  neck_xp: Int!
  neck_metadata: Int!
  ring_id: Int!
  ring_xp: Int!
  ring_metadata: Int!
  beast_health: Int!
  stat_points_available: Int!
  mutated: Int!
  previous_level: Int!
  new_level: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type UpgradesAvailable {
  id: String!
  owner: String!
  adventurer_id: Int!
  no_message: Int!
  last_action: Int!
  health: Int!
  xp: Int!
  strength: Int!
  dexterity: Int!
  vitality: Int!
  intelligence: Int!
  wisdom: Int!
  charisma: Int!
  luck: Int!
  gold: Int!
  weapon_id: Int!
  weapon_xp: Int!
  weapon_metadata: Int!
  chest_id: Int!
  chest_xp: Int!
  chest_metadata: Int!
  head_id: Int!
  head_xp: Int!
  head_metadata: Int!
  waist_id: Int!
  waist_xp: Int!
  waist_metadata: Int!
  foot_id: Int!
  foot_xp: Int!
  foot_metadata: Int!
  hand_id: Int!
  hand_xp: Int!
  hand_metadata: Int!
  neck_id: Int!
  neck_xp: Int!
  neck_metadata: Int!
  ring_id: Int!
  ring_xp: Int!
  ring_metadata: Int!
  beast_health: Int!
  stat_points_available: Int!
  mutated: Int!
  items: String!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type DiscoveredHealth {
  id: String!
  owner: String!
  adventurer_id: Int!
  no_message: Int!
  last_action: Int!
  health: Int!
  xp: Int!
  strength: Int!
  dexterity: Int!
  vitality: Int!
  intelligence: Int!
  wisdom: Int!
  charisma: Int!
  luck: Int!
  gold: Int!
  weapon_id: Int!
  weapon_xp: Int!
  weapon_metadata: Int!
  chest_id: Int!
  chest_xp: Int!
  chest_metadata: Int!
  head_id: Int!
  head_xp: Int!
  head_metadata: Int!
  waist_id: Int!
  waist_xp: Int!
  waist_metadata: Int!
  foot_id: Int!
  foot_xp: Int!
  foot_metadata: Int!
  hand_id: Int!
  hand_xp: Int!
  hand_metadata: Int!
  neck_id: Int!
  neck_xp: Int!
  neck_metadata: Int!
  ring_id: Int!
  ring_xp: Int!
  ring_metadata: Int!
  beast_health: Int!
  stat_points_available: Int!
  mutated: Int!
  amount: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type DiscoveredGold {
  id: String!
  owner: String!
  adventurer_id: Int!
  no_message: Int!
  last_action: Int!
  health: Int!
  xp: Int!
  strength: Int!
  dexterity: Int!
  vitality: Int!
  intelligence: Int!
  wisdom: Int!
  charisma: Int!
  luck: Int!
  gold: Int!
  weapon_id: Int!
  weapon_xp: Int!
  weapon_metadata: Int!
  chest_id: Int!
  chest_xp: Int!
  chest_metadata: Int!
  head_id: Int!
  head_xp: Int!
  head_metadata: Int!
  waist_id: Int!
  waist_xp: Int!
  waist_metadata: Int!
  foot_id: Int!
  foot_xp: Int!
  foot_metadata: Int!
  hand_id: Int!
  hand_xp: Int!
  hand_metadata: Int!
  neck_id: Int!
  neck_xp: Int!
  neck_metadata: Int!
  ring_id: Int!
  ring_xp: Int!
  ring_metadata: Int!
  beast_health: Int!
  stat_points_available: Int!
  mutated: Int!
  amount: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type DodgedObstacle {
  id: String!
  owner: String!
  adventurer_id: Int!
  no_message: Int!
  last_action: Int!
  health: Int!
  xp: Int!
  strength: Int!
  dexterity: Int!
  vitality: Int!
  intelligence: Int!
  wisdom: Int!
  charisma: Int!
  luck: Int!
  gold: Int!
  weapon_id: Int!
  weapon_xp: Int!
  weapon_metadata: Int!
  chest_id: Int!
  chest_xp: Int!
  chest_metadata: Int!
  head_id: Int!
  head_xp: Int!
  head_metadata: Int!
  waist_id: Int!
  waist_xp: Int!
  waist_metadata: Int!
  foot_id: Int!
  foot_xp: Int!
  foot_metadata: Int!
  hand_id: Int!
  hand_xp: Int!
  hand_metadata: Int!
  neck_id: Int!
  neck_xp: Int!
  neck_metadata: Int!
  ring_id: Int!
  ring_xp: Int!
  ring_metadata: Int!
  beast_health: Int!
  stat_points_available: Int!
  mutated: Int!
  obstacle_id: Int!
  obstacle_level: Int!
  obstacle_damage_taken: Int!
  obstacle_damage_location: Int!
  obstacle_critical_hit: Int!
  obstacle_adventurer_xp_reward: Int!
  obstacle_item_xp_reward: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type HitByObstacle {
  id: String!
  owner: String!
  adventurer_id: Int!
  no_message: Int!
  last_action: Int!
  health: Int!
  xp: Int!
  strength: Int!
  dexterity: Int!
  vitality: Int!
  intelligence: Int!
  wisdom: Int!
  charisma: Int!
  luck: Int!
  gold: Int!
  weapon_id: Int!
  weapon_xp: Int!
  weapon_metadata: Int!
  chest_id: Int!
  chest_xp: Int!
  chest_metadata: Int!
  head_id: Int!
  head_xp: Int!
  head_metadata: Int!
  waist_id: Int!
  waist_xp: Int!
  waist_metadata: Int!
  foot_id: Int!
  foot_xp: Int!
  foot_metadata: Int!
  hand_id: Int!
  hand_xp: Int!
  hand_metadata: Int!
  neck_id: Int!
  neck_xp: Int!
  neck_metadata: Int!
  ring_id: Int!
  ring_xp: Int!
  ring_metadata: Int!
  beast_health: Int!
  stat_points_available: Int!
  mutated: Int!
  obstacle_id: Int!
  obstacle_level: Int!
  obstacle_damage_taken: Int!
  obstacle_damage_location: Int!
  obstacle_critical_hit: Int!
  obstacle_adventurer_xp_reward: Int!
  obstacle_item_xp_reward: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type AmbushedByBeast {
  id: String!
  owner: String!
  adventurer_id: Int!
  no_message: Int!
  last_action: Int!
  health: Int!
  xp: Int!
  strength: Int!
  dexterity: Int!
  vitality: Int!
  intelligence: Int!
  wisdom: Int!
  charisma: Int!
  luck: Int!
  gold: Int!
  weapon_id: Int!
  weapon_xp: Int!
  weapon_metadata: Int!
  chest_id: Int!
  chest_xp: Int!
  chest_metadata: Int!
  head_id: Int!
  head_xp: Int!
  head_metadata: Int!
  waist_id: Int!
  waist_xp: Int!
  waist_metadata: Int!
  foot_id: Int!
  foot_xp: Int!
  foot_metadata: Int!
  hand_id: Int!
  hand_xp: Int!
  hand_metadata: Int!
  neck_id: Int!
  neck_xp: Int!
  neck_metadata: Int!
  ring_id: Int!
  ring_xp: Int!
  ring_metadata: Int!
  beast_health: Int!
  stat_points_available: Int!
  mutated: Int!
  seed: Int!
  slayed_beast_id: Int!
  tier: Int!
  item_type: Int!
  level: Int!
  special1: Int!
  special2: Int!
  special3: Int!
  damage_dealt: Int!
  critical_hit: Int!
  xp_earned_adventurer: Int!
  xp_earned_items: Int!
  gold_earned: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}

type DiscoveredBeast {
    id: String!
  owner: String!
  adventurer_id: Int!
  no_message: Int!
  last_action: Int!
  health: Int!
  xp: Int!
  strength: Int!
  dexterity: Int!
  vitality: Int!
  intelligence: Int!
  wisdom: Int!
  charisma: Int!
  luck: Int!
  gold: Int!
  weapon_id: Int!
  weapon_xp: Int!
  weapon_metadata: Int!
  chest_id: Int!
  chest_xp: Int!
  chest_metadata: Int!
  head_id: Int!
  head_xp: Int!
  head_metadata: Int!
  waist_id: Int!
  waist_xp: Int!
  waist_metadata: Int!
  foot_id: Int!
  foot_xp: Int!
  foot_metadata: Int!
  hand_id: Int!
  hand_xp: Int!
  hand_metadata: Int!
  neck_id: Int!
  neck_xp: Int!
  neck_metadata: Int!
  ring_id: Int!
  ring_xp: Int!
  ring_metadata: Int!
  beast_health: Int!
  stat_points_available: Int!
  mutated: Int!
  seed: Int!
  slayed_beast_id: Int!
  tier: Int!
  item_type: Int!
  level: Int!
  special1: Int!
  special2: Int!
  special3: Int!
  damage_dealt: Int!
  critical_hit: Int!
  xp_earned_adventurer: Int!
  xp_earned_items: Int!
  gold_earned: Int!
  tx_hash: String!
  created_at: Int!
  created_at_block: Int!
}
